include:
  - board: nice_nano
    shield: choctopus44
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: hillside48_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: hillside48_right
  - board: nice_nano
    shield: settings_reset
